# Generated by Django 5.0.1 on 2024-02-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConservationForum', '0002_remove_topic_post_post_topic_remove_topic_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='species',
        ),
        migrations.AddField(
            model_name='post',
            name='species',
            field=models.ManyToManyField(to='ConservationForum.species'),
        ),
    ]
