git# Generated by Django 5.0.1 on 2024-02-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConservationForum', '0003_remove_topic_species_post_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
