# Generated by Django 5.0.1 on 2024-02-09 03:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models



def forwards_func(apps, schema_editor):
    # Get the model 'User' from the 'auth' app
    User = apps.get_model('auth', 'User')


class Migration(migrations.Migration):

    dependencies = [
        ('ConservationForum', '0004_alter_post_date'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
            ]
options={
    'verbose_name': 'user',
    'verbose_name_plural': 'users',
    'abstract': False,
}
managers=[
    ('objects', django.contrib.auth.models.UserManager()),
]